name: Gerar tag e realizar deploy

on:
  pull_request:
    types:
      - closed

jobs:
  deployment:
    runs-on: ubuntu-latest

    env:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
      MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: copiar settings-conatus-repository.xml
      run: |
        echo "${MAVEN_SETTINGS}" > ./settings.xml
        envsubst < ./settings.xml > $HOME/.m2/settings.xml
        export MAVEN_HOME=$HOME/.m2/settings.xml

    - name: Gerar Tag e Fazer Deploy
      if: github.event.pull_request.merged == true
      run: |
        # Obtém a versão do pom
        VERSION=$(grep -m1 '<version>' "./pom.xml" | sed -n 's/.*<version>\(.*\)<\/version>.*/\1/p')

        # Gerar uma tag com a versão do pom
        git tag "$VERSION"
        git push origin "$VERSION"

        # Obtém o artifactId do projeto Maven
        ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)

        # Configurar o nome do arquivo JAR com base no artifactId e versão
        JAR_NAME="$ARTIFACT_ID-$VERSION.jar"

        # Realiza o build do projeto e especifica o nome do arquivo JAR
        mvn clean install -DskipTests -Dmaven.finalName=$JAR_NAME

        # Realiza o deploy no Nexus usando o perfil nexus e especifica o nome do arquivo JAR
        mvn deploy -DskipTests -Pnexus -Dfile=target/$JAR_NAME -DpomFile=pom.xml -DaltDeploymentRepository=nexus::default::http://${NEXUS_HOST}/repository/mvn-conatus-sa/

    - name: Comentar no PR
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 O Pull Request foi implantado com sucesso no ambiente'
            })
